#.
#The amount of liquid a Classic Blaze Enchanter can hold (mB).
#[@cui:RequiresReload:server]
# Default: 4000
# Range: > 1000
classicBlazeForgerFluidCapacity = 4000
#.
#Experience cost coefficient of Classic Blaze Enchanter regular enchanting.
#[@cui:RequiresReload:server]
# Default: 1.0
# Range: 0.009999999776482582 ~ 3.4028234663852886E38
classicBlazeForgerNormalEnchantingCostCoefficient = 1.0
#.
#Experience cost coefficient of Classic Blaze Enchanter super enchanting.
#[@cui:RequiresReload:server]
# Default: 1.0
# Range: 0.009999999776482582 ~ 3.4028234663852886E38
classicBlazeForgerSuperEnchantingCostCoefficient = 1.0
#.
#Probability that a cursed Classic Blaze Enchanter super enchants resulting in a drop in enchantment level
#[@cui:RequiresReload:server]
# Default: 0.25
# Range: 0.009999999776482582 ~ 3.4028234663852886E38
classicBlazeForgerSuperEnchantingCurseLevelDroppingRate = 0.25
