#List of post-processing chains to skip injection
inject_post_chain_blacklist = []
#Screen capture mode
capture_mode = "B"
#Upscale ratio factor
upscale_ratio = 1.4198
#Algorithm used for upscaling
upscale_algo = "fsr2"
#Disable Super Resolution when using vanilla rendering.
disable_upscale_on_vanilla = false
#This option enables the use of a compatibility shader compiler for compiling shaders when set to true.
compat_shader_compiler = false
#Sharpness adjustment factor
sharpness = 0.3102
#Force disable shader pack compatibility mode.
force_disable_shader_compat = false
#Enable super-resolution upscaling
enable_upscale = false
#Pause game when GUI is open
pause_game_on_gui = false

[debug]
	#Skip Vulkan initialization (auto-set based on OS)
	skip_init_vulkan = true
	#Enable RenderDoc integration (auto-disabled on incompatible OS)
	enable_render_doc = false
	#Enable debug mode
	enable_debug = false
	#Enable ImGui debug interface (auto-disabled on incompatible OS)
	enable_imgui = false
	#Dump shaders for debugging purposes
	debug_dump_shader = false
	#Enable more detailed performance profiling for advanced analysis.
	enable_detailed_profiling = false

#Algorithm special configuration
[special]

	[special.sgsr2]
		variant = "CS_2"

	[special.fsr1]
		fp16 = true

	[special.fsr2]
		version = "V233"
		fp16 = true

[experiment]
	#Generate motion vectors for advanced effects
	generate_motion_vectors = false

[dataset]
	dataset_path = "msrDataset"
	enable_dataset_generator = false
